export const themes = {
  darkMode: {
    TERMINAL_BACKGROUND_COLOR: '#000000',
    TERMINAL_REPLY_COLOR: '#e6e6fa',
    TERMINAL_DIRECTORY_PROMPT_COLOR: '#07bd07',
    TERMINAL_COMMAND_PROMPT_COLOR: '#f5f5f5',
    TERMINAL_LS_FILE_COLOR: '#dbff00',
    TERMINAL_LS_FOLDER_COLOR: '#007bff',
  },
  solarized: {
    TERMINAL_BACKGROUND_COLOR: '#002b36',
    TERMINAL_REPLY_COLOR: '#839496',
    TERMINAL_DIRECTORY_PROMPT_COLOR: '#b58900',
    TERMINAL_COMMAND_PROMPT_COLOR: '#93a1a1',
    TERMINAL_LS_FILE_COLOR: '#2aa198',
    TERMINAL_LS_FOLDER_COLOR: '#268bd2',
  },
  dracula: {
    TERMINAL_BACKGROUND_COLOR: '#282a36',
    TERMINAL_REPLY_COLOR: '#f8f8f2',
    TERMINAL_DIRECTORY_PROMPT_COLOR: '#50fa7b',
    TERMINAL_COMMAND_PROMPT_COLOR: '#ff79c6',
    TERMINAL_LS_FILE_COLOR: '#bd93f9',
    TERMINAL_LS_FOLDER_COLOR: '#ffb86c',
  },
  lightMode: {
    TERMINAL_BACKGROUND_COLOR: '#f7f7f7',
    TERMINAL_REPLY_COLOR: '#333333',
    TERMINAL_DIRECTORY_PROMPT_COLOR: '#006400',
    TERMINAL_COMMAND_PROMPT_COLOR: '#000000',
    TERMINAL_LS_FILE_COLOR: '#0000ff',
    TERMINAL_LS_FOLDER_COLOR: '#8b0000',
  },
  kanagawa: {
    TERMINAL_BACKGROUND_COLOR: '#1f1f28', // Sakura background
    TERMINAL_REPLY_COLOR: '#c8c093', // Muted ivory reply color
    TERMINAL_DIRECTORY_PROMPT_COLOR: '#ffa066', // Warm orange for directories
    TERMINAL_COMMAND_PROMPT_COLOR: '#dcd7ba', // Light beige for command input
    TERMINAL_LS_FILE_COLOR: '#7e9cd8', // Cool blue for files
    TERMINAL_LS_FOLDER_COLOR: '#a3d4d5', // Soft cyan for folders
  },
}
